### ISSUE TITLE
Categorise Badges?

### ISSUE THREAD

**Issue by shrirambalaji** [snift/snift-api#38]
Currently the Badges are sent without a category indicating what type of security badge it is. 

I'd like to categorise them to be shown better in the UI ( in some way, not sure how that'd be, but could be category score which when sorta summed up leads to the actual score. Thinking the UI would be Similar to what [lighthouse](https://developers.google.com/web/tools/lighthouse/v3/scoring) does for websites.

Following is the categorization I have in mind:

### Network Protection
- HTTP_SECURE
- HTTPS_ONLY
- LATEST_HTTP
- LATEST_TLS

### Content Security
- CSP_ENABLED
- XSS_PROTECT
- CLICKJACKING_PROTECT

### User Privacy
- NO_SNIFF
- ENSURE_PRIVACY

### Eavesdropping and Spoofing Protection
- PUBLIC_KEY_PINNING_ENABLED
- EMAIL_SPOOFING_PROTECT

@maruthi-adithya let me know your thoughts.

**Comment by maruthi-adithya** [comment]
Good idea. We can do this.
